language: r
cache: packages
pandoc_version: 1.19.2.1

env:
  global:
    - secure: "mKDLqgUYE5m1i47z1CaJT6rhYjjYwhWNQfMM6JxvT5RrRnWHfN6VZ/z2d6G537uVO6EuHNc7ew40x5iOUFTEWaRriv2Kiyqwu5QvYidHZgQz6nuWG+TSRdMzH5lXjdr9bX1uesAnQuHd46ufVJeKft/aWbuXrKdIT45J6SlTx89phP/7yaLsmwxN32LP7H44LZDiLFFJEfNbIxk3ozzffXvXbjHI3wPUS9tWuy2r+1rxxeqKz5c7MthUMwfV60w37O+mWv17u3zk6AN22xM+lyyQrNTEPL41Yv9CbuuODqPyP/WE6K3jqBvPSi4Vi7heXSnCKBkutsgUKTJeNGmndE6ZKxBv/1kOxWUWBtK+5wq/KHAXI138RUTWHnHhUpKjiuP4O0TsS/RzD/5WOyzyX28R0snMNconADC1i7y386ycqe6MOrJP5VRJ3VhttM+eCXAO8K4mPJjolB6ZsbbQuNv5AzApj5lF6UUBEWvShoI12XUmkGB/kZ1ZEJPD5zPcIELGa3EezR5yCuMOpVJVqBz/y2gBu59CeyKAPdEPpPmJxFzDMzPgmypLhhvrmm5RgauiohBcVgjlC7aGsF4A55bS3HmPsPy7lH21sMLbQeLz9Mhk+LUW60YqHVNEL3CwEH6ac7ENNsx3zRJxwnfjO1lUkmwFwU3n2uqwVN7T6Yo="

script:
  - ./_build.sh
  - ./_deploy.sh
